let cod = 123;
let employeeCod = cod;
console.log(typeof (employeeCod));
let employee = {};
let employee2 = {};
employee2.nome = 'John';
employee2.code = 123;
console.log(typeof (employee2.nome));
console.log(typeof (employee2.code));
console.log(employee2.nome);
console.log(employee2.code);
